### PR TITLE
Akash scrum58

### PR DESCRIPTION
**Pull request by akashmisra1**

### CODE REVIEW

**Comment by akashmisra1** [comment]
Download button needs to be fixed. Currently it downloads the PDF file of the first button on Vocoder Basics

**Review by andrewpeng02 — APPROVED** [review]
Nit: Center the text in the close button
image

**Review by buchanmatthew — APPROVED** [review]

**Comment by buchanmatthew** [comment]
> Download button needs to be fixed. Currently it downloads the PDF file of the first button on Vocoder Basics

if youre referring to my ticket i can fix this just lmk what i need to change

**Review by DannySchultzDev — APPROVED** [review]

**Review by msmudano — COMMENTED** [review]
Great start for the education page!

**Review by msmudano — APPROVED** [review]

**Pull request merged**
