### PR TITLE
supposedly i linked the backend idk if it really works tho

### PR DESCRIPTION
**Pull request by buchanmatthew**

### CODE REVIEW

**Comment by buchanmatthew** [comment]
i tested it and the sounds still play so hopefully we are good

**Review by andrewpeng02 — CHANGES_REQUESTED** [review]
It doesn't seem like vocoder.js is integrated into the frontend quite yet, running the vocoder still uses the backend function

**Comment by buchanmatthew** [comment]
before you close this PR,   keep it open so i can experiment with it.

**Comment by buchanmatthew** [comment]
im just gonna merge it i dont really know what im doing w the bugfixes required

**Pull request merged**
