### PR TITLE
Export/Download a completed audio file ran thru the vocoder

### PR DESCRIPTION
**Pull request by buchanmatthew**

### CODE REVIEW

**Comment by andrewpeng02** [comment]
That's not the correct file? The user has to be able to run the vocoder with arbitrary inputs and download the output of the vocoder

**Comment by buchanmatthew** [comment]
> That's not the correct file? The user has to be able to run the vocoder with arbitrary inputs and download the output of the vocoder

sorry, im not sure i know what you mean. where does the user give arbitrary inputs? which section is dedicated to the vocoder output?

**Comment by andrewpeng02** [comment]
The user selects the modulator and carrier signals, clicks on the run button and generated the output. that's what we want to be able to download

**Comment by buchanmatthew** [comment]
will update when changed

**Review by msmudano — DISMISSED** [review]

**Comment by andrewpeng02** [comment]
Also note that our user story says they can export in multiple formats, like wav or MP4 for example

**Comment by buchanmatthew** [comment]
did a little bit more , dont really know what im doing here hope it works

**Comment by andrewpeng02** [comment]
does the download work?

**Comment by buchanmatthew** [comment]
> does the download work?

idk

**Comment by andrewpeng02** [comment]
can you still not run the vocoder??

**Comment by buchanmatthew** [comment]
> can you still not run the vocoder??

i can run it just not through nextjs for some reason, so looking at the code it should work just not on my machine for some reason

**Review by DannySchultzDev — APPROVED** [review]

**Review by msmudano — APPROVED** [review]

**Review by akashmisra1 — APPROVED** [review]
Looks fine. We can create a bug ticket next sprint to address the feature not working on your device

**Pull request merged**
