### PR TITLE
Allow user to customize vocoder parameters (filters_per_band, etc) that voclib.h takes in the command line

### PR DESCRIPTION
**Pull request by buchanmatthew**
added some customize parameters

### CODE REVIEW

**Comment by andrewpeng02** [comment]
Where is the functionality? Right now it doesn't do anything, but I expect it to actually change the output of the vococet

**Review by msmudano — APPROVED** [review]

**Review by msmudano — APPROVED** [review]
Looks like a good start to the feature

**Comment by buchanmatthew** [comment]
still working on this. might need some typescript pointers but i'll let you guys know.

**Comment by buchanmatthew** [comment]
reopened bc i want to just get the first part of this out while i work on the voclib.h

**Pull request merged**
