### PR TITLE
Allow user the option to create a custom midi to be used as carrier signal input

### PR DESCRIPTION
**Pull request by msmudano**
Adds a third option in carrier signal dropdown called "custom midi" which lets the user select a custom note sequence to be used as the carrier signal. Full functionality to be added

### CODE REVIEW

**Review by buchanmatthew — APPROVED** [review]
great

**Review by akashmisra1 — APPROVED** [review]
Works as intended

**Comment by andrewpeng02** [comment]
how will you handle the time dimension? like selecting a note that sounds from t=0 to 1, and selecting a note that sounds from t=0.5 to 2?

**Comment by msmudano** [comment]
> how will you handle the time dimension? like selecting a note that sounds from t=0 to 1, and selecting a note that sounds from t=0.5 to 2?

As of right now each note selected in the array is worth same amount of time. However, I do plan to allow that functionality as I continue to work with it.

**Review by DannySchultzDev — APPROVED** [review]
Makes sense to add this.

**Pull request merged**
