### PR TITLE
SCRUM-54

### PR DESCRIPTION
**Pull request by buchanmatthew**
made able to export learning content as pdf

### CODE REVIEW

**Comment by andrewpeng02** [comment]
Looks good

**Review by msmudano — COMMENTED** [review]
Looks good to me!

**Review by DannySchultzDev — APPROVED** [review]
For the commit on adding the pdf:
Comment could be more clear.
Reviewed and validated purpose over teams.

**Comment by buchanmatthew** [comment]
will make comments more clear next time but for now lets merge this thang

**Pull request merged**
